version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - REACT_APP_FIRESTORE_EMULATOR_HOST=firestore_emulator:8200
      - REACT_APP_FIRESTORE_PROJECT_ID=kibana111
    volumes:
      - ./node_modules:/app/node_modules
      - ./src:/app/src
      - ./public:/app/public
    ports:
      - 3000:3000
    stdin_open: true
    restart: always
    container_name: app
    depends_on:
      - firestore_emulator
  firestore_emulator:
    image: perrystallings/cloud-firestore-emulator
    environment:
      - FIRESTORE_PROJECT_ID=kibana111
    ports:
      - 8200:8080
    networks:
      - webapp
    container_name: firestore_emulator
networks:
  webapp:
    driver: bridge
